<a href="https://colab.research.google.com/github/SHuBhAM71205/pytorch/blob/main/Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title imports

import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
print(torch.__version__)

In [ ]:

## intro to tensor

## scelar

scelar=torch.tensor([5])
scelar

In [ ]:
#vector

vector=torch.tensor([1,2,3])
vector.ndim
vector

In [ ]:
# matrix

matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix
matrix.ndim


In [ ]:
#tensor

tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor.shape)
print(tensor.ndim)


In [ ]:
# @title learn 2 random tensor


In [ ]:
## random tensor

rand_tnsr=torch.rand(5,4,6,2)

print(rand_tnsr.ndim)

In [ ]:
## image random tensor

img_rand_tensor=torch.rand(size=(244,244,3))



In [ ]:
# @title Zeros and Ones

zeros=torch.zeros(10,10)
print(zeros)

ones=torch.ones(size=(10,10))


In [ ]:
# @title range of tensor

range_tensor=torch.arange(0,10,step=2,dtype=torch.int16)

print(range_tensor)


zero_like=torch.zeros_like(range_tensor)
print(zero_like)

In [ ]:
# @title tensor datatypes
# @title float 32 int

common paraneter with the torch.tensor

In [ ]:
int_32_tensor=torch.tensor([1,2,3,4],dtype=torch.int32)
float_32_tensor=torch.tensor([1,2,3,4],dtype=torch.float32)

int_32_tensor * float_32_tensor

## suprisingly works

int_32_tensor.dtype,int_32_tensor.device,int_32_tensor.shape


In [ ]:
# @title Formatted string printing

name = "Alice"
age = 30
height = 1.75

# Using f-strings for formatted output
print(f"My name is {name}, I am {age} years old, and my height is {height:.2f} meters.")

# You can also perform calculations within f-strings
print(f"In 10 years, I will be {age + 10} years old.")

# Formatting with alignment and padding
number = 123
print(f"Padded number: {number:05d}") # Pad with leading zeros to a width of 5

text = "Hello"
print(f"Centered text: {text:^10}") # Center the text within a width of 10

In [ ]:
# @title manuppilating tensor

## opration + - * /


tensorA=torch.tensor([1,2,3,4])

tensorB = tensorA + 10 ## element wise 10 convert to [10,10,10,10]

# same for the oth



print(tensorB)

In [ ]:
# @title Matrix Multiplication


# element wise and matrix
print(tensorA * 10)
# element wise *

# in dot()

print(f"matrix multiplication : {tensorA @ tensorA}")
torch.matmul(tensorA,tensorA)


In [ ]:
# @title shape error

# if the shape dont match for mul it give this error

tensorA= torch.tensor([[1,2],
                       [2,3],
                       [3,4]])


tensorB= torch.tensor([[7,8],
                       [9,10],
                       [11,12]])

torch.mm(tensorA,tensorB.T) ## run fine
# torch.mm(tensorA,tensorB) ## dont run fine 3,2 @ 3,2 give shape error


In [ ]:
# @title max min min add


tensorA= torch.tensor([[1,2],
                       [2,3],
                       [3,4]])

print(f"min of th e tensorA {torch.min(tensorA)},\nmax of tensorA {torch.max(tensorA)},\nmin of tensorA {torch.mean(tensorA.type(torch.float32))},\nsum of the tensorA {torch.sum(tensorA)}")


In [ ]:
# @title arg min max for return pos

- Reshaping, stacking, squeezing and unsqueezing tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x=torch.arange(0,10)

# add
# reshape should have same element
# dont change original shape of x
print(x.reshape(2,5))

# it make change in original
print(x.view(5,2))



In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=1) ## dim 0 do is it scale the same val in vertical 1 scales in horizontal
print(x_stacked)

In [ ]:
# squezze or unsquese

x_squeezed=x.squeeze()
print(x_squeezed) # make it one d vector

x_unsqueezed=x_squeezed.unsqueeze(dim=0
                                  )
print(x_unsqueezed)

In [ ]:
# @title indexing


# same as numpy

tensorA= torch.rand((1,3,3),dtype=torch.float32)
print(tensorA)
print(tensorA[0][2])

print(tensorA[0,:,2])

In [128]:
array= np.arange(1,5)
print(array)

torch_array=torch.from_numpy(array)
print(torch_array)

[1 2 3 4]
tensor([1, 2, 3, 4])


In [133]:
# @title reproduciblity

# random ou t of random

torch.rand(3,3)

# to reduce randomness come seed

tensA=torch.rand(3,3)
tensB=torch.rand(3,3)

print(tensA)
print(tensB)
print(tensA==tensB)

RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)

torch_randA=torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
torch_randB=torch.rand(3,3)

print(torch_randA)
print(torch_randB)
print(torch_randB == torch_randA)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])
tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [133]:
# @title Running on the gpu

